id = "constructor"
name = "constructor"
width = 80
height = 80
color = [100, 255, 50, 255] # R, G, B, A

[[ports]]
type = "input"
content = "item"
x = 0
y = 40

[[ports]]
type = "output"
content = "item"
x = 80
y = 40
