id = "miner_mk1"
name = "Miner MK1"
width = 120
height = 120
color = [50, 255, 100, 255] # R, G, B, A

[[ports]]
type = "input"
content = "item"
x = 0
y = 60

[[ports]]
type = "output"
content = "item"
x = 120
y = 60
