id = "smelter_mk1"
name = "Smelter"
width = 100
height = 80
color = [255, 100, 50, 255] # R, G, B, A


[[ports]]
type = "input"
content = "item"
x = 0
y = 40

[[ports]]
type = "output"
content = "item"
x = 100
y = 40
